# !! Might deprecate 
core_vault_sunbird_ekstep_api_key:  #this we will fill post deployed onboard consumer job
core_vault_sunbird_encryption_key:       #Random hash to encrypt data e.g. 6A6hEJr8
core_vault_kong__test_jwt:            #this will fill post deployment of onboard consumer job

############# Core #######################
####### Secrets #######

core_vault_sunbird_trampoline_secret: # some 8 digit password for keycloak sso user e.g. 10000000
core_vault_postgres_password: #postgres password e.g. 8rrMDnBQg
core_vault_sunbird_azure_storage_key :  #Azure storage account key
core_vault_docker_registry_url: "https://index.docker.io/v1" # use this value if using dockerhub
core_vault_docker_registry_user:  #Your docker userID e.g demoTest
core_vault_docker_registry_password: #Your docker password e.g. 6A6hEJr8
core_vault_proxy_site_key: |+        # Generate the site key and site crt by using certbot.sh script in sunbird-devops folder

core_vault_proxy_site_crt: |+

core_vault_ansible_vault_password: 
 
################### DONT FILL THESE VARIABLES INITIALLY ###################

core_vault_sunbird_sso_publickey:  # Get After Keycloak Deployment
core_vault_sunbird_api_auth_token: #Take the jwt token api-management-test-user from Jenkins job OnboardConsumers and update core_vault_sunbird_api_auth_token if using KP and DP along with core
core_vault_sunbird_keycloak_user_federation_provider_id:      # Get after keycloak deployment

######################## Not mandatory ###################################
core_vault_sunbird_fcm_account_key: ""
core_vault_sunbird_google_oauth_clientSecret: 
core_vault_mail_server_password: ''
core_vault_keycloak_api_management_user_password: admin
core_vault_keystore_password: sunbird  #Password to use for encrypting cassandra keystore. Use a strong password.
vault_core_url_shortner_access_token: "" # Url shortner access token for learning-service; only if url_shortner enabled
core_vault_sunbird_sso_username: admin
core_vault_sunbird_sso_password: admin
core_vault_keycloak_password: "admin"
core_vault_grafana_admin_password: "sunbird"
core_vault_truststore_password: "sunbird" # Password for cassandra trust store
core_vault_trampoline_secret: "deep-secret" ## any 8 character value
core_vault_msg_91_auth_key:

# Portal one google sso
core_vault_sunbird_google_oauth_clientId_portal: 
core_vault_sunbird_google_oauth_clientSecret_portal: 
core_vault_sunbird_google_captcha_site_key_portal: 
core_vault_sunbird_google_keycloak_secret: 

# Oauth for logger kibana
core_vault_kibana_google_client_id: 
core_vault_kibana_google_client_secret: 
core_vault_kibana_cookie_secret: kibanaoauth # Cookie secret for kibana Oauth

####################### END OF VARS ##########################################

#NOT REQUIRED TO EDIT ##############################
core_vault_badger_admin_password: "sunbird"
core_vault_badging_authorization_key: 
core_vault_jenkins_admin_username: "" #### if it is not required will remove
core_vault_jenkins_admin_password: "" #### if it is not required will remove
core_vault_proxy_prometheus_admin_creds: "admin"
core_vault_postgres_username: postgres  # dont change this value
core_vault_grafana_editor_password: "sunbird"
core_vault_grafana_dashboards_git_repo_url_with_credentails: "https://github.com/project-sunbird/grafana-dashboards.git"
core_vault_monitor_alerts_slack_url: ""

##### Release-2.3.0 ###################
core_vault_enc_entry_password: test # encryption password for the enc service
core_vault_enc_master_pass: test # encryption password for the keys

##### release-2.6 vars #####
core_vault_graph_passport_key: #copy value from variable lp_vault_graph_passport_key from KnowledgePlatform/Secrets.yml

##### release-2.7 vars #####
artifact_azure_account_sas: # generate a sas for the azure blob for entire storage accout with write and read access.

############################
# public storage account with content conatiner.(Azure storage key)
sunbird_azure_public_storage_account_key:

# Used to store the private contents of the storage account.(Azure storage key)
sunbird_azure_private_storage_account_key:

# used to store backups for or application DB's (Azure storage key)
sunbird_azure_management_storage_account_key:

# This account need to be private to store jenkins build artifacts which will be used commonly between environments.(Azure storage key)
sunbird_azure_artifact_storage_account_key:
### release-2.8.0 #####
core_vault_sunbird_sso_client_secret: #get the lms client secret from keycloak, post keycloak configuration
